### ISSUE TITLE
Zotero ribbon doesn't add to tab bars in Word

### ISSUE THREAD

**Issue by Kylvan-8** [farag2/Install-Office#17]
Hello,
Is any settings that needs to be changed to allow the ribbon tab to be executed correctly and display in word ?

Zotero says that's not a Zotero issue.

**Comment by farag2** [comment]
I do not know what Zotero is. I provide a script to download the latest  geniune Microsoft Office. I receive a feedback regarding the script work, not any 3rd party add-ins.
